const postData = [
  {
    id: 1,
    hikeName: 'Fun in the sun',
    trailId: 'trail_id',
    description: 'I went on this hike and had an absolute blast. I saw a nice waterfall halfway through the hike.',
    pictureArray: ['placeholder_blob', 'placeholder_blob', 'placeholder_blob'],
    userId: 1,
    difficulty: '4',
    review: '5',
  },
  {
    id: 2,
    hikeName: 'Almost Died',
    trailId: 'trail_id',
    description: "I was attacked by a wild mongoose. Scariest 18 seconds of my life. wouldn't recommend.",
    pictureArray: ['placeholder_blob', 'placeholder_blob', 'placeholder_blob'],
    userId: 2,
    difficulty: '3',
    review: '1',
  },
  {
    id: 3,
    hikeName: 'Snowy at the top',
    trailId: 'trail_id',
    description:
      'There was still snow at the top, making the steep part 3/4 of the way up pretty difficult. bring spikes!',
    pictureArray: ['placeholder_blob', 'placeholder_blob', 'placeholder_blob'],
    userId: 3,
    difficulty: '4',
    review: '4',
  },
  {
    id: 4,
    hikeName: 'Birds everywhere',
    trailId: 'trail_id',
    description: 'There are many birds along this trail that you can feed',
    pictureArray: ['placeholder_blob', 'placeholder_blob', 'placeholder_blob'],
    userId: 4,
    difficulty: '3',
    review: '5',
  },
  {
    id: 5,
    hikeName: 'Cliff Climb!',
    trailId: 'trail_id',
    description:
      'This was one of the steepest and hardest hikes ive ever done! well worth the effort though with an amazing view at the top!',
    pictureArray: ['placeholder_blob', 'placeholder_blob', 'placeholder_blob'],
    userId: 5,
    difficulty: '5',
    review: '5',
  },
];
export default postData;
